[package]
name = "neofold"
version = "0.1.0"
authors = ["heartsh <heartsh@heartsh.io>"]
description = "NeoFold Program, Program for Maximum-expected-accuracy Estimations of RNA Secondary Structures by Incorporating Homologous-RNA sequences"

[dependencies]
bio-seq-algos = "0.1"
rna-algos = "0.1"
itertools = "0.7"
lazy_static = "0.1"
time = "0.1"
scoped_threadpool = "0.1"
getopts = "0.2"
bio = "0.9"
num_cpus = "1.0"
strap = {path = "../strap"}

[lib]
path = "src/lib.rs"
name = "neofold"
